server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tomato_bookstore?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": false
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %highlight(%5p) %clr([%-40.40logger{39}]){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info
    "[com.tomato.bookstore]": debug
    "[org.hibernate]": warn
    "[org.springframework]": warn

app:
  jwt:
    secret: ${JWT_SECRET:tomatobookstoresecretkeyiswhatyouguess}
    expiration: 86400000 # 24 小时
  security:
    public-paths: /,/api,/api/user/login,/api/user/register,/api/orders/notify
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:5173}

alipay:
  appId: ${ALIPAY_APP_ID}
  appPrivateKey: ${ALIPAY_PRIVATE_KEY}
  alipayPublicKey: ${ALIPAY_PUBLIC_KEY}
  notifyUrl: ${ALIPAY_TUNNEL_URL}${server.servlet.context-path}/orders/notify
  returnUrl: ${ALIPAY_TUNNEL_URL}${server.servlet.context-path}/orders/return
  serverUrl: ${ALIPAY_SERVER_URL:https://openapi-sandbox.dl.alipaydev.com/gateway.do}
