server:
  port: ${SERVER_PORT:8080}

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tomato_bookstore?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %highlight{%-5level} %clr([%thread]){red} %cyan{%logger{15}} : %msg%n"
  level:
    root: info
    "[com.tomato.bookstore]": debug
    "[org.hibernate]": warn
    "[org.springframework]": warn
