application:
  title: tomato-bookstore
  version: 0.1.0-dev

# JWT 配置
app:
  jwt:
    secret: tomatobookstoresecretkeythatissecuretomatobookstoresecretkeythatissecure
    expiration: 86400000 # 24 小时

spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
