application:
  title: tomato-bookstore
  version: 0.1.0-dev

spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data/users.sql, classpath:data/products.sql, classpath:data/specifications.sql, classpath:data/advertisements.sql, classpath:data/carts.sql, classpath:data/orders.sql
